//
//  DailySummaryTests.swift
//  ExpensesTests
//
//  Created by Borja Arias Drake on 29.05.2021..
//  Copyright © 2021 Borja Arias Drake. All rights reserved.
//

import XCTest
import CoreExpenses
import CoreDataPersistence
import Combine

class DailySummaryTests: XCTestCase {
    
    private static var presenter: ShowDailyEntriesPresenter<ImmediateScheduler, ImmediateScheduler>!
    private static var selectedCategoryDataSource: CoreDataCategoryDataSource!
    private static var setCategoryInteractor: SetCategoryFilterInteractor!
    
    override static func setUp() {
        let tg = TestDataGenerator()
        let context = tg.generate_sync()

        TestDataGenerator.printAll(context)
        selectedCategoryDataSource = CoreDataCategoryDataSource(context: context)
        setCategoryInteractor = SetCategoryFilterInteractor(dataSource: selectedCategoryDataSource)
        let monthlySummaryDataSource = DailyCoreDataExpensesDataSource(coreDataContext:context,
                                                                       selectedCategoryDataSource: selectedCategoryDataSource)
        presenter = ShowDailyEntriesPresenter(interactor: ExpensesSummaryInteractor(dataSource: monthlySummaryDataSource),
                                              subscriptionScheduler: ImmediateScheduler.shared,
                                              receiveOnScheduler: ImmediateScheduler.shared)
        
    }

    override func setUp() {
        DailySummaryTests.presenter.bind()
    }

    override func tearDown() {
        DailySummaryTests.presenter.unbind()
    }
    
}

// MARK: - Category Filter tests
extension DailySummaryTests {
    
    func test_daily_breakdown_all_categories() throws {
        XCTAssert(DailySummaryTests.presenter.sections.count == 9)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: "$20.00"),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: "-$15.00"),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: "-$320.90"),
                                 Test.Expense(title: "31", value: "$5,000.00"),
                                 Test.Expense(title: "32", value: "")], // <------- FIX-ME
                                inSection: 8,
                                named: "Jan 2013",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: "-$45.00"),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: "-$90.00"),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: "")],
                                inSection: 7,
                                named: "Feb 2013",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: "$500.00"),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: "")],
                                inSection: 6,
                                named: "Nov 2013",
                                presenter: DailySummaryTests.presenter)
                    
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: "-$150.00"),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: "-$11.40"),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: "$3,779.10"),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")],
                                inSection: 5,
                                named: "Mar 2014",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: "$5,000.00"),
                                 Test.Expense(title: "31", value: "")],
                                inSection: 4,
                                named: "Sep 2014",
                                presenter: DailySummaryTests.presenter)
 
         Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: "-$45.00"),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")],
                                inSection: 3,
                                named: "Oct 2014",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                Test.Expense(title: "2", value: ""),
                                Test.Expense(title: "3", value: ""),
                                Test.Expense(title: "4", value: ""),
                                Test.Expense(title: "5", value: ""),
                                Test.Expense(title: "6", value: ""),
                                Test.Expense(title: "7", value: ""),
                                Test.Expense(title: "8", value: ""),
                                Test.Expense(title: "9", value: ""),
                                Test.Expense(title: "10", value: ""),
                                Test.Expense(title: "11", value: ""),
                                Test.Expense(title: "12", value: ""),
                                Test.Expense(title: "13", value: ""),
                                Test.Expense(title: "14", value: ""),
                                Test.Expense(title: "15", value: ""),
                                Test.Expense(title: "16", value: ""),
                                Test.Expense(title: "17", value: "-$45.00"),
                                Test.Expense(title: "18", value: ""),
                                Test.Expense(title: "19", value: ""),
                                Test.Expense(title: "20", value: ""),
                                Test.Expense(title: "21", value: ""),
                                Test.Expense(title: "22", value: ""),
                                Test.Expense(title: "23", value: ""),
                                Test.Expense(title: "24", value: ""),
                                Test.Expense(title: "25", value: ""),
                                Test.Expense(title: "26", value: ""),
                                Test.Expense(title: "27", value: ""),
                                Test.Expense(title: "28", value: ""),
                                Test.Expense(title: "29", value: ""),
                                Test.Expense(title: "30", value: ""),
                                Test.Expense(title: "31", value: "")],
                               inSection: 2,
                               named: "Nov 2014",
                               presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                Test.Expense(title: "2", value: ""),
                                Test.Expense(title: "3", value: ""),
                                Test.Expense(title: "4", value: ""),
                                Test.Expense(title: "5", value: ""),
                                Test.Expense(title: "6", value: ""),
                                Test.Expense(title: "7", value: ""),
                                Test.Expense(title: "8", value: ""),
                                Test.Expense(title: "9", value: ""),
                                Test.Expense(title: "10", value: ""),
                                Test.Expense(title: "11", value: ""),
                                Test.Expense(title: "12", value: ""),
                                Test.Expense(title: "13", value: ""),
                                Test.Expense(title: "14", value: ""),
                                Test.Expense(title: "15", value: ""),
                                Test.Expense(title: "16", value: ""),
                                Test.Expense(title: "17", value: ""),
                                Test.Expense(title: "18", value: ""),
                                Test.Expense(title: "19", value: ""),
                                Test.Expense(title: "20", value: "-$90.00"),
                                Test.Expense(title: "21", value: ""),
                                Test.Expense(title: "22", value: ""),
                                Test.Expense(title: "23", value: ""),
                                Test.Expense(title: "24", value: ""),
                                Test.Expense(title: "25", value: ""),
                                Test.Expense(title: "26", value: ""),
                                Test.Expense(title: "27", value: ""),
                                Test.Expense(title: "28", value: ""),
                                Test.Expense(title: "29", value: ""),
                                Test.Expense(title: "30", value: ""),
                                Test.Expense(title: "31", value: ""),
                                Test.Expense(title: "32", value: "")],
                               inSection: 1,
                               named: "Dec 2014",
                               presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                Test.Expense(title: "2", value: ""),
                                Test.Expense(title: "3", value: ""),
                                Test.Expense(title: "4", value: ""),
                                Test.Expense(title: "5", value: ""),
                                Test.Expense(title: "6", value: ""),
                                Test.Expense(title: "7", value: ""),
                                Test.Expense(title: "8", value: ""),
                                Test.Expense(title: "9", value: ""),
                                Test.Expense(title: "10", value: ""),
                                Test.Expense(title: "11", value: "-$163.20"),
                                Test.Expense(title: "12", value: ""),
                                Test.Expense(title: "13", value: ""),
                                Test.Expense(title: "14", value: ""),
                                Test.Expense(title: "15", value: ""),
                                Test.Expense(title: "16", value: ""),
                                Test.Expense(title: "17", value: ""),
                                Test.Expense(title: "18", value: ""),
                                Test.Expense(title: "19", value: ""),
                                Test.Expense(title: "20", value: ""),
                                Test.Expense(title: "21", value: ""),
                                Test.Expense(title: "22", value: ""),
                                Test.Expense(title: "23", value: ""),
                                Test.Expense(title: "24", value: ""),
                                Test.Expense(title: "25", value: ""),
                                Test.Expense(title: "26", value: ""),
                                Test.Expense(title: "27", value: ""),
                                Test.Expense(title: "28", value: ""),
                                Test.Expense(title: "29", value: ""),
                                Test.Expense(title: "30", value: ""),
                                Test.Expense(title: "31", value: ""),
                                Test.Expense(title: "32", value: "")],
                               inSection: 0,
                               named: "Aug 2015",
                               presenter: DailySummaryTests.presenter)
    }
    
    func test_daily_breakdown_food() throws {
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Food", iconName: "", color: .red))

        XCTAssert(DailySummaryTests.presenter.sections.count == 2)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: "-$30.00"),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: "-$15.00"),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")], // <------- FIX-ME
                                inSection: 1,
                                named: "Jan 2013",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: "-$150.00"),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: "-$11.40"),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")], // <------- FIX-ME
                                inSection: 0,
                                named: "Mar 2014",
                                presenter: DailySummaryTests.presenter)
    }
    
    func test_daily_breakdown_bills() throws {
        
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Bills", iconName: "", color: .red))
        XCTAssert(DailySummaryTests.presenter.sections.count == 4)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: "-$45.00"),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: "")]
                                ,
                                inSection: 3,
                                named: "Feb 2013",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: "-$45.00"),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")],
                                inSection: 2,
                                named: "Oct 2014",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: "-$45.00"),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: "")],
                                inSection: 1,
                                named: "Nov 2014",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: "-$90.00"),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")],
                                inSection: 0,
                                named: "Dec 2014",
                                presenter: DailySummaryTests.presenter)
    }

    func test_daily_breakdown_travel() throws {
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Travel", iconName: "", color: .red))
        XCTAssert(DailySummaryTests.presenter.sections.count == 3)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: "-$320.90"),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")]
                                ,
                                inSection: 2,
                                named: "Jan 2013",
                                presenter: DailySummaryTests.presenter)
      
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: "$3,779.10"),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")],
                                inSection: 1,
                                named: "Mar 2014",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: "-$163.20"),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: ""),
                                 Test.Expense(title: "32", value: "")],
                                inSection: 0,
                                named: "Aug 2015",
                                presenter: DailySummaryTests.presenter)
        
        
    }

    func test_daily_breakdown_income() throws {
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Income", iconName: "", color: .red))
        XCTAssert(DailySummaryTests.presenter.sections.count == 3)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: "$50.00"),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: "$5,000.00"),
                                 Test.Expense(title: "32", value: "")]
                                ,
                                inSection: 2,
                                named: "Jan 2013",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: "$500.00"),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: ""),
                                 Test.Expense(title: "31", value: "")],
                                inSection: 1,
                                named: "Nov 2013",
                                presenter: DailySummaryTests.presenter)
        
        Test.assertEqualEntries([Test.Expense(title: "1", value: ""),
                                 Test.Expense(title: "2", value: ""),
                                 Test.Expense(title: "3", value: ""),
                                 Test.Expense(title: "4", value: ""),
                                 Test.Expense(title: "5", value: ""),
                                 Test.Expense(title: "6", value: ""),
                                 Test.Expense(title: "7", value: ""),
                                 Test.Expense(title: "8", value: ""),
                                 Test.Expense(title: "9", value: ""),
                                 Test.Expense(title: "10", value: ""),
                                 Test.Expense(title: "11", value: ""),
                                 Test.Expense(title: "12", value: ""),
                                 Test.Expense(title: "13", value: ""),
                                 Test.Expense(title: "14", value: ""),
                                 Test.Expense(title: "15", value: ""),
                                 Test.Expense(title: "16", value: ""),
                                 Test.Expense(title: "17", value: ""),
                                 Test.Expense(title: "18", value: ""),
                                 Test.Expense(title: "19", value: ""),
                                 Test.Expense(title: "20", value: ""),
                                 Test.Expense(title: "21", value: ""),
                                 Test.Expense(title: "22", value: ""),
                                 Test.Expense(title: "23", value: ""),
                                 Test.Expense(title: "24", value: ""),
                                 Test.Expense(title: "25", value: ""),
                                 Test.Expense(title: "26", value: ""),
                                 Test.Expense(title: "27", value: ""),
                                 Test.Expense(title: "28", value: ""),
                                 Test.Expense(title: "29", value: ""),
                                 Test.Expense(title: "30", value: "$5,000.00"),
                                 Test.Expense(title: "31", value: "")],
                                inSection: 0,
                                named: "Sep 2014",
                                presenter: DailySummaryTests.presenter)

    }

    
}
