//
//  DailySummaryTests.swift
//  ExpensesTests
//
//  Created by Borja Arias Drake on 29.05.2021..
//  Copyright © 2021 Borja Arias Drake. All rights reserved.
//

import XCTest
import CoreExpenses
import CoreDataPersistence
import Combine

class DailySummaryTests: XCTestCase {
    
    private static var presenter: ShowDailyEntriesPresenter<ImmediateScheduler, ImmediateScheduler>!
    private static var selectedCategoryDataSource: CoreDataCategoryDataSource!
    private static var setCategoryInteractor: SetCategoryFilterInteractor!
    private var cancellable: AnyCancellable?
    
    override static func setUp() {
        let tg = TestDataGenerator()
        let context = tg.generate_sync()

        TestDataGenerator.printAll(context)
        selectedCategoryDataSource = CoreDataCategoryDataSource(context: context)
        setCategoryInteractor = SetCategoryFilterInteractor(dataSource: selectedCategoryDataSource as! CategoryDataSource)
        let monthlySummaryDataSource = DailyCoreDataExpensesDataSource(coreDataContext:context,
                                                                       selectedCategoryDataSource: selectedCategoryDataSource)
        presenter = ShowDailyEntriesPresenter(interactor: ExpensesSummaryInteractor(dataSource: monthlySummaryDataSource),
                                              subscriptionScheduler: ImmediateScheduler.shared,
                                              receiveOnScheduler: ImmediateScheduler.shared)
        
    }

    override func setUp() {
        cancellable?.cancel()
        cancellable = nil
        DailySummaryTests.presenter.bind()
    }

    override func tearDown() {
        cancellable?.cancel()
        cancellable = nil
        DailySummaryTests.presenter.unbind()
    }
    
}

// MARK: - Category Filter tests
extension DailySummaryTests {
    
    func test_daily_breakdown_all_categories() throws {
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: "$20.00"),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: "-$15.00"),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "-$320.90"),
                                       Test.Expense(title: "31", value: "$5,000.00")],
                                      inSection: 8,
                                      sectionName: "Jan 2013",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 2)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: "-$45.00"),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: "-$90.00"),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: "")],
                                      inSection: 7,
                                      sectionName: "Feb 2013",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: "$500.00"),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "")],
                                      inSection: 6,
                                      sectionName: "Nov 2013",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
        
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: "-$150.00"),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: "-$11.40"),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: "$3,779.10"),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 5,
                                      sectionName: "Mar 2014",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
        
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "$5,000.00")],
                                      inSection: 4,
                                      sectionName: "Sep 2014",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: "-$45.00"),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 3,
                                      sectionName: "Oct 2014",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
        
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: "-$45.00"),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "")],
                                      inSection: 2,
                                      sectionName: "Nov 2014",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
        
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: "-$90.00"),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 1,
                                      sectionName: "Dec 2014",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: "-$163.20"),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 0,
                                      sectionName: "Aug 2015",
                                      sectionCount: 9,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
    }
    
    func test_daily_breakdown_food() throws {
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Food", iconName: "", color: .red))

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: "-$30.00"),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: "-$15.00"),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: ""),],
                                      inSection: 1,
                                      sectionName: "Jan 2013",
                                      sectionCount: 2,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 2)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: "-$150.00"),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: "-$11.40"),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: ""),],
                                      inSection: 0,
                                      sectionName: "Mar 2014",
                                      sectionCount: 2,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
    }
    
    func test_daily_breakdown_bills() throws {
        
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Bills", iconName: "", color: .red))
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: "-$45.00"),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: "")],
                                      inSection: 3,
                                      sectionName: "Feb 2013",
                                      sectionCount: 4,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 2)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: "-$45.00"),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 2,
                                      sectionName: "Oct 2014",
                                      sectionCount: 4,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: "-$45.00"),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "")],
                                      inSection: 1,
                                      sectionName: "Nov 2014",
                                      sectionCount: 4,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: "-$90.00"),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 0,
                                      sectionName: "Dec 2014",
                                      sectionCount: 4,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
    }

    func test_daily_breakdown_travel() throws {
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Travel", iconName: "", color: .red))
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "-$320.90"),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 2,
                                      sectionName: "Jan 2013",
                                      sectionCount: 3,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 2)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: "$3,779.10"),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 1,
                                      sectionName: "Mar 2014",
                                      sectionCount: 3,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: "-$163.20"),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "")],
                                      inSection: 0,
                                      sectionName: "Aug 2015",
                                      sectionCount: 3,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
    }

    func test_daily_breakdown_income() throws {
        DailySummaryTests.setCategoryInteractor.filter(by: ExpenseCategory(name: "Income", iconName: "", color: .red))
        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: "$50.00"),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: ""),
                                       Test.Expense(title: "31", value: "$5,000.00")],
                                      inSection: 2,
                                      sectionName: "Jan 2013",
                                      sectionCount: 3,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 2)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: "$500.00"),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "")],
                                      inSection: 1,
                                      sectionName: "Nov 2013",
                                      sectionCount: 3,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)

        Test.assertSectionsEventually([Test.Expense(title: "1", value: ""),
                                       Test.Expense(title: "2", value: ""),
                                       Test.Expense(title: "3", value: ""),
                                       Test.Expense(title: "4", value: ""),
                                       Test.Expense(title: "5", value: ""),
                                       Test.Expense(title: "6", value: ""),
                                       Test.Expense(title: "7", value: ""),
                                       Test.Expense(title: "8", value: ""),
                                       Test.Expense(title: "9", value: ""),
                                       Test.Expense(title: "10", value: ""),
                                       Test.Expense(title: "11", value: ""),
                                       Test.Expense(title: "12", value: ""),
                                       Test.Expense(title: "13", value: ""),
                                       Test.Expense(title: "14", value: ""),
                                       Test.Expense(title: "15", value: ""),
                                       Test.Expense(title: "16", value: ""),
                                       Test.Expense(title: "17", value: ""),
                                       Test.Expense(title: "18", value: ""),
                                       Test.Expense(title: "19", value: ""),
                                       Test.Expense(title: "20", value: ""),
                                       Test.Expense(title: "21", value: ""),
                                       Test.Expense(title: "22", value: ""),
                                       Test.Expense(title: "23", value: ""),
                                       Test.Expense(title: "24", value: ""),
                                       Test.Expense(title: "25", value: ""),
                                       Test.Expense(title: "26", value: ""),
                                       Test.Expense(title: "27", value: ""),
                                       Test.Expense(title: "28", value: ""),
                                       Test.Expense(title: "29", value: ""),
                                       Test.Expense(title: "30", value: "$5,000.00")],
                                      inSection: 0,
                                      sectionName: "Sep 2014",
                                      sectionCount: 3,
                                      cancellable: &cancellable,
                                      presenter: DailySummaryTests.presenter,
                                      testCase: self,
                                      checkAfter: 1)
    }
}
