//
//  DailySummaryTests.swift
//  ExpensesTests
//
//  Created by Borja Arias Drake on 29.05.2021..
//  Copyright © 2021 Borja Arias Drake. All rights reserved.
//

import XCTest
import CoreExpenses
import CoreDataPersistence
import Combine

class DailySummaryTests: XCTestCase {
    
    private var presenter: ShowDailyEntriesPresenter<ImmediateScheduler, ImmediateScheduler>!
    private var selectedCategoryDataSource: CategoryDataSource!
    private var setCategoryInteractor: SetCategoryFilterInteractor!
    private var cancellable: AnyCancellable?
    
    func setupDependencies() async throws {
        let tg = TestDataGenerator()
        let context = try await tg.generate()
        TestDataGenerator.printAll(context)
        selectedCategoryDataSource = CoreDataCategoryDataSource(context: context)
        setCategoryInteractor = SetCategoryFilterInteractor(dataSource: selectedCategoryDataSource)
        let dailySummaryDataSource = DailyCoreDataExpensesDataSource(coreDataContext:context,
                                                                     selectedCategoryDataSource: selectedCategoryDataSource)
        presenter = ShowDailyEntriesPresenter(interactor: ExpensesSummaryInteractor(dataSource: dailySummaryDataSource),
                                              subscriptionScheduler: ImmediateScheduler.shared,
                                              receiveOnScheduler: ImmediateScheduler.shared)
        cancellable?.cancel()
        cancellable = nil
        presenter.bind()
    }
    
    override func tearDown() {
        cancellable?.cancel()
        cancellable = nil
        presenter.unbind()
    }
}

// MARK: - Category Filter tests
extension DailySummaryTests {
    
    func test_daily_breakdown_all_categories() async throws {
        try await setupDependencies()
        
        Test.assertSectionsEventually([Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: "$20.00"),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: "-$15.00"),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "-$320.90"),
                                                                          Test.Expense(title: "31", value: "$5,000.00")],
                                                        sectionIndex: 1,
                                                        sectionName: "Jan 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: "-$45.00"),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: "-$90.00"),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Feb 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: "$500.00"),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Nov 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: "-$150.00"),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: "-$11.40"),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: "$3,779.10"),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Mar 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "$5,000.00")],
                                                        sectionIndex: 0,
                                                        sectionName: "Sep 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: "-$45.00"),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Oct 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: "-$45.00"),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Nov 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: "-$90.00"),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Dec 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: "-$163.20"),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Aug 2015")
                                       
                                       
                                      ],
                                      cancellable: &cancellable,
                                      presenter: presenter,
                                      testCase: self)
    }
    
    func test_daily_breakdown_food() async throws {
        try await setupDependencies()
        setCategoryInteractor.filter(by: ExpenseCategory(name: "Food", iconName: "", color: .red))
        
        Test.assertSectionsEventually([Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: "-$30.00"),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: "-$15.00"),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: ""),],
                                                        sectionIndex: 1,
                                                        sectionName: "Jan 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: "-$150.00"),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: "-$11.40"),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: ""),],
                                                        sectionIndex: 0,
                                                        sectionName: "Mar 2014")
                                      ],
                                      cancellable: &cancellable,
                                      presenter: presenter,
                                      testCase: self)
    }
    
    func test_daily_breakdown_bills() async throws {
        try await setupDependencies()
        setCategoryInteractor.filter(by: ExpenseCategory(name: "Bills", iconName: "", color: .red))
        Test.assertSectionsEventually([Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: "-$45.00"),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: "")],
                                                        sectionIndex: 1,
                                                        sectionName: "Feb 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: "-$45.00"),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Oct 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: "-$45.00"),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Nov 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: "-$90.00"),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Dec 2014")
                                      ],
                                      cancellable: &cancellable,
                                      presenter: presenter,
                                      testCase: self)
    }
    
    func test_daily_breakdown_travel() async throws {
        try await setupDependencies()
        setCategoryInteractor.filter(by: ExpenseCategory(name: "Travel", iconName: "", color: .red))
        Test.assertSectionsEventually([Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "-$320.90"),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 1,
                                                        sectionName: "Jan 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: "$3,779.10"),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Mar 2014"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: "-$163.20"),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Aug 2015"),
                                      ],
                                      cancellable: &cancellable,
                                      presenter: presenter,
                                      testCase: self)
    }
    
    func test_daily_breakdown_income() async throws {
        try await setupDependencies()
        setCategoryInteractor.filter(by: ExpenseCategory(name: "Income", iconName: "", color: .red))
        Test.assertSectionsEventually([Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: "$50.00"),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: ""),
                                                                          Test.Expense(title: "31", value: "$5,000.00")],
                                                        sectionIndex: 1,
                                                        sectionName: "Jan 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: "$500.00"),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "")],
                                                        sectionIndex: 0,
                                                        sectionName: "Nov 2013"),
                                       Test.SectionInfo(expectedEntries: [Test.Expense(title: "1", value: ""),
                                                                          Test.Expense(title: "2", value: ""),
                                                                          Test.Expense(title: "3", value: ""),
                                                                          Test.Expense(title: "4", value: ""),
                                                                          Test.Expense(title: "5", value: ""),
                                                                          Test.Expense(title: "6", value: ""),
                                                                          Test.Expense(title: "7", value: ""),
                                                                          Test.Expense(title: "8", value: ""),
                                                                          Test.Expense(title: "9", value: ""),
                                                                          Test.Expense(title: "10", value: ""),
                                                                          Test.Expense(title: "11", value: ""),
                                                                          Test.Expense(title: "12", value: ""),
                                                                          Test.Expense(title: "13", value: ""),
                                                                          Test.Expense(title: "14", value: ""),
                                                                          Test.Expense(title: "15", value: ""),
                                                                          Test.Expense(title: "16", value: ""),
                                                                          Test.Expense(title: "17", value: ""),
                                                                          Test.Expense(title: "18", value: ""),
                                                                          Test.Expense(title: "19", value: ""),
                                                                          Test.Expense(title: "20", value: ""),
                                                                          Test.Expense(title: "21", value: ""),
                                                                          Test.Expense(title: "22", value: ""),
                                                                          Test.Expense(title: "23", value: ""),
                                                                          Test.Expense(title: "24", value: ""),
                                                                          Test.Expense(title: "25", value: ""),
                                                                          Test.Expense(title: "26", value: ""),
                                                                          Test.Expense(title: "27", value: ""),
                                                                          Test.Expense(title: "28", value: ""),
                                                                          Test.Expense(title: "29", value: ""),
                                                                          Test.Expense(title: "30", value: "$5,000.00")],
                                                        sectionIndex: 0,
                                                        sectionName: "Sep 2014"),
                                      ],
                                      cancellable: &cancellable,
                                      presenter: presenter,
                                      testCase: self)
    }
}
